### ISSUE TITLE
[hotfix #26] Error on save upload/save artifact

### ISSUE THREAD

**Issue by santanche** [datasci4health/harena-manager#26]
The service to upload artifacts (POST request, path: /artifact) is crashing when requested. See below the message shown by harena-manager when the upload is requested:
~~~
undefined

b829391c-eb2f-4a49-8ddc-b6404d77b032

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined

    at Object.openSync (fs.js:426:3)

    at ArtifactController.store (/home/santanche/git/harena-manager/src/adonisjs/app/Controllers/Http/v1/ArtifactController.js:36:7)

    at Server._routeHandler (/home/santanche/git/harena-manager/src/adonisjs/node_modules/@adonisjs/framework/src/Server/index.js:121:31)

    at MiddlewareBase._resolveMiddleware (/home/santanche/git/harena-manager/src/adonisjs/node_modules/@adonisjs/middleware-base/index.js:195:28)

    at Runnable._invoke (/home/santanche/git/harena-manager/src/adonisjs/node_modules/co-compose/src/Runnable.js:76:42)

    at once (/home/santanche/git/harena-manager/src/adonisjs/node_modules/co-compose/src/Runnable.js:73:34)

    at f (/home/santanche/git/harena-manager/src/adonisjs/node_modules/once/once.js:25:25)

    at Auth.handle (/home/santanche/git/harena-manager/src/adonisjs/node_modules/@adonisjs/auth/src/Middleware/Auth.js:127:11)
~~~

**Comment by faguim** [comment]
@santanche can you inform the file and block of code in harena-space that call the POST /artifact? In guess the postman has an error on call a POST request with files on the body of message, then i can not reproduce the error using postman.

**Comment by santanche** [comment]
The function is in the file https://github.com/datasci4health/harena-space/blob/master/src/adonisjs/public/author/js/dcc-author-server-proxy.js

See the function: uploadArtifact

However, the last time that I used Postman (before the changes concerning the case deletion) it was working for the /artifact POST service.

**Comment by faguim** [comment]
@santanche Hotfix solved, waiting pull request revision to get in production environment
